version: '3'
services:
  bot:
    build:
      context: .
      args:
        NODE_ENV: development
    env_file: projects/bot/.env
    volumes:
      - ./projects:/app/projects
    entrypoint: ["yarn", "run", "start:dev"]
    ports:
      - "8000:80"
    networks:
      - backend

  db:
    image: mongo
    networks:
      - backend

networks:
  backend: {}
