version: '3'
services:
  bot:
    build:
      dockerfile: projects/bot/Dockerfile
      context: .
      args:
        NODE_ENV: development
    env_file: projects/bot/.env
    volumes:
      - ./projects:/app/projects
    entrypoint: [ "yarn", "run", "start:dev" ]
    ports:
      - "8000:80"

  web:
    build:
      dockerfile: projects/web/Dockerfile
      context: .
      args:
        NODE_ENV: development
    env_file: projects/web/.env
    volumes:
      - ./projects:/app/projects
    entrypoint: [ "yarn", "run", "start:dev" ]
    ports:
      - "8080:80"

  db:
    image: mongo
    volumes:
      - db:/data/db
      - db:/data/configdb
    ports:
      - "27017:27017"

  blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite --blobHost 0.0.0.0 -l /workspace
    volumes:
      - azurite:/workspace
      - azurite:/data
    ports:
      - "10000:10000"

volumes:
  db:
  azurite:
