version: '3'
services:
  bot:
    build:
      context: .
      args:
        NODE_ENV: development
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./sounds:/app/sounds
      - ./logs:/app/logs
    entrypoint: ["yarn", "run", "start:dev"]
    ports:
      - "8000:80"
