version: '3'
services:
  bot:
    build:
      context: projects/bot
      args:
        NODE_ENV: development
    env_file: projects/bot/.env
    volumes:
      - ./projects/bot/src:/app/src
      - ./projects/bot/sounds:/app/sounds
      - ./projects/bot/logs:/app/logs
    entrypoint: ["yarn", "run", "start:dev"]
    ports:
      - "8000:80"
