name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build sounds
        working-directory: projects/sounds
        run: yarn run build
      - name: Lint sounds
        working-directory: projects/sounds
        run: yarn run lint
      - name: Build bot
        working-directory: projects/bot
        run: yarn run build
      - name: Lint bot
        working-directory: projects/bot
        run: yarn run lint

  deploy:
    if: github.ref_name == 'master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: uncledave
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Run migrations
        working-directory: projects/mongo
        run: yarn run up
        env:
          MIGRATIONS_CONNECTION_URI: ${{ secrets.MIGRATIONS_CONNECTION_URI }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: uncledave/botman:latest
