name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build sounds
        working-directory: projects/sounds
        run: yarn run build
      - name: Lint sounds
        working-directory: projects/sounds
        run: yarn run lint
      - name: Build bot
        working-directory: projects/bot
        run: yarn run build
      - name: Lint bot
        working-directory: projects/bot
        run: yarn run lint

  migrate-database:
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Run migrations
        working-directory: projects/mongo
        run: yarn run up
        env:
          MIGRATIONS_CONNECTION_URI: ${{ secrets.MIGRATIONS_CONNECTION_URI }}

  deploy-bot:
    if: github.ref_name == 'master'
    needs: migrate-database
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: uncledave
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: uncledave/botman:latest

  deploy-ui:
    if: github.ref_name == 'master'
    needs: migrate-database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: botman-web-p
          publish-profile: ${{ secrets.UI_PUBLISH_PROFILE }}
          package: projects/ui-server
