name: CI
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn run lint

  deploy:
    if: github.ref_name == 'master'
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: uncledave
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: uncledave/botman:latest
