name: Deploy

on:
  push:
    branches:
      - master

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  migrate-database:
    name: Migrate database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: yarn
      - name: Install dependencies
        run: yarn --pure-lockfile
      - name: Run migrations
        working-directory: projects/mongo
        run: yarn run up
        env:
          MIGRATIONS_CONNECTION_URI: ${{ secrets.MIGRATIONS_CONNECTION_URI }}

  deploy-bot:
    name: Deploy bot
    needs: migrate-database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: uncledave
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: uncledave/botman:latest
          file: projects/bot/Dockerfile

  deploy-web:
    name: Deploy web
    needs: migrate-database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: uncledave
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: uncledave/botman-web:latest
          file: projects/web/Dockerfile
          build-args: |
            BOT_WEBSOCKETS_URL=${{ vars.BOT_WEBSOCKETS_URL }}
